import path from "path";
import { fileURLToPath } from "url";
import { config } from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
config({ path: path.resolve(__dirname, "../../.env") });

import { db } from "./client.js";
import { giftCatalogItems } from "./schema.js";

const items = [
  // New parent / baby
  {
    title: "Organic cotton baby onesie set",
    description: "Soft 3-pack onesies in neutral colors, 0-3 months",
    priceMin: 18,
    priceMax: 28,
    tags: ["new_parent", "baby", "practical", "clothing"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Sleepless parent care kit",
    description: "Eye mask, herbal tea, lip balm, and hand cream for tired parents",
    priceMin: 22,
    priceMax: 35,
    tags: ["new_parent", "self_care", "sentimental", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup", "digital"],
  },
  {
    title: "Baby milestone cards",
    description: "Photo prop cards for monthly baby photos (0-12 months)",
    priceMin: 12,
    priceMax: 20,
    tags: ["new_parent", "sentimental", "keepsake"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup", "digital"],
  },
  {
    title: "Sound machine for nursery",
    description: "Portable white noise machine with multiple sounds",
    priceMin: 25,
    priceMax: 45,
    tags: ["new_parent", "baby", "practical"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Gift card: baby store",
    description: "$50 e-gift card for major baby retailer (instant delivery)",
    priceMin: 25,
    priceMax: 100,
    tags: ["new_parent", "baby", "digital", "flexible"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Meal delivery subscription (1 week)",
    description: "Pre-made meals delivered for new parents",
    priceMin: 45,
    priceMax: 80,
    tags: ["new_parent", "practical", "food"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  // Coffee / tea
  {
    title: "Specialty coffee sampler",
    description: "4 small-batch single-origin coffees, whole bean",
    priceMin: 28,
    priceMax: 42,
    tags: ["coffee", "tea", "food", "practical"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Ceramic pour-over set",
    description: "Pour-over dripper, carafe, and 6-month filter pack",
    priceMin: 35,
    priceMax: 55,
    tags: ["coffee", "practical", "kitchen"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Tea advent calendar",
    description: "24 days of premium loose-leaf teas in tins",
    priceMin: 32,
    priceMax: 48,
    tags: ["tea", "sentimental", "food"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Starbucks e-gift card",
    description: "Digital gift card, any amount, instant delivery",
    priceMin: 5,
    priceMax: 100,
    tags: ["coffee", "digital", "flexible"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Local roaster gift box",
    description: "Two bags of seasonal roast + mug from local roaster",
    priceMin: 38,
    priceMax: 55,
    tags: ["coffee", "local", "sentimental"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Matcha starter kit",
    description: "Ceremonial matcha, whisk, bowl, and recipe card",
    priceMin: 40,
    priceMax: 65,
    tags: ["tea", "coffee", "practical", "wellness"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  // Sentimental
  {
    title: "Personalized photo book",
    description: "Hardcover photo book, 20 pages, upload photos online",
    priceMin: 25,
    priceMax: 45,
    tags: ["sentimental", "keepsake", "personalized"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Engraved jewelry (name or date)",
    description: "Sterling silver necklace or bracelet with custom text",
    priceMin: 35,
    priceMax: 75,
    tags: ["sentimental", "jewelry", "personalized"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Custom star map print",
    description: "Night sky on a specific date/location, framed print",
    priceMin: 30,
    priceMax: 55,
    tags: ["sentimental", "art", "personalized"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Letterbox / time capsule kit",
    description: "Box with prompts to write letters to open in 1/5/10 years",
    priceMin: 18,
    priceMax: 32,
    tags: ["sentimental", "keepsake", "experience"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Handwritten note + small keepsake",
    description: "Curated small item (keychain, charm) with handwritten card",
    priceMin: 15,
    priceMax: 35,
    tags: ["sentimental", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  // Practical
  {
    title: "Quality wool socks (3-pack)",
    description: "Merino or blended hiking/comfort socks",
    priceMin: 22,
    priceMax: 38,
    tags: ["practical", "clothing", "comfort"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Portable power bank 10000mAh",
    description: "Compact USB-C power bank with fast charging",
    priceMin: 25,
    priceMax: 45,
    tags: ["practical", "tech", "gadget"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Desk organizer set",
    description: "Pen holder, tray, cable clips in wood or metal",
    priceMin: 20,
    priceMax: 40,
    tags: ["practical", "office", "home"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Insulated lunch bag + containers",
    description: "Bento-style containers with insulated bag",
    priceMin: 28,
    priceMax: 48,
    tags: ["practical", "food", "kitchen"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Multi-tool / pocket knife",
    description: "Compact multi-tool with knife, screwdriver, bottle opener",
    priceMin: 30,
    priceMax: 60,
    tags: ["practical", "outdoor", "gadget"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Quality umbrella (wind-resistant)",
    description: "Compact folding umbrella, durable",
    priceMin: 25,
    priceMax: 45,
    tags: ["practical", "everyday"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  // Self-care
  {
    title: "Bath bomb and candle set",
    description: "3 bath bombs + soy candle in calming scent",
    priceMin: 22,
    priceMax: 38,
    tags: ["self_care", "relaxation", "spa"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Aromatherapy diffuser kit",
    description: "Ultrasonic diffuser with 3 essential oil blends",
    priceMin: 35,
    priceMax: 55,
    tags: ["self_care", "wellness", "home"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Skincare mini set",
    description: "Cleanser, moisturizer, serum in travel sizes from known brand",
    priceMin: 28,
    priceMax: 50,
    tags: ["self_care", "beauty", "skincare"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Meditation app subscription (1 year)",
    description: "Gift subscription to Headspace or Calm",
    priceMin: 45,
    priceMax: 70,
    tags: ["self_care", "digital", "wellness"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Yoga mat + block set",
    description: "Non-slip mat with alignment lines and foam block",
    priceMin: 32,
    priceMax: 55,
    tags: ["self_care", "fitness", "wellness"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Journal and pen set",
    description: "Hardcover journal with refillable pen",
    priceMin: 18,
    priceMax: 35,
    tags: ["self_care", "sentimental", "writing"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  // Last-minute digital
  {
    title: "Amazon e-gift card",
    description: "Email delivery, any amount, arrives in minutes",
    priceMin: 5,
    priceMax: 200,
    tags: ["digital", "flexible", "last_minute"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Spotify Premium (3 months)",
    description: "Digital gift card for Spotify Premium",
    priceMin: 30,
    priceMax: 30,
    tags: ["digital", "music", "subscription"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Audible credit (1 book)",
    description: "One audiobook credit, instant delivery",
    priceMin: 15,
    priceMax: 15,
    tags: ["digital", "books", "audio"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Uber Eats e-gift card",
    description: "Digital gift card for food delivery",
    priceMin: 10,
    priceMax: 100,
    tags: ["digital", "food", "last_minute"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Apple App Store / Google Play gift card",
    description: "Digital code for apps, games, subscriptions",
    priceMin: 10,
    priceMax: 100,
    tags: ["digital", "tech", "flexible"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Masterclass or Skillshare (1 month)",
    description: "Gift access to online learning platform",
    priceMin: 15,
    priceMax: 35,
    tags: ["digital", "learning", "experience"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  // Experience / subscription
  {
    title: "Movie theater gift card",
    description: "Chain theater e-gift card, redeem at box office or online",
    priceMin: 25,
    priceMax: 50,
    tags: ["experience", "entertainment", "digital"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Local restaurant e-gift card",
    description: "Support local: e-gift card for dine-in or takeout",
    priceMin: 25,
    priceMax: 100,
    tags: ["experience", "food", "local"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital", "pickup"],
  },
  {
    title: "Flower delivery (same-day possible)",
    description: "Bouquet from local florist or 1-800-Flowers",
    priceMin: 35,
    priceMax: 75,
    tags: ["sentimental", "flowers", "last_minute"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Wine or craft beer delivery",
    description: "Curated 2-bottle set with note (where legal)",
    priceMin: 40,
    priceMax: 70,
    tags: ["food", "experience", "adult"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Puzzle or board game",
    description: "Family-friendly board game or 500-piece puzzle",
    priceMin: 20,
    priceMax: 45,
    tags: ["experience", "family", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Book by favorite author",
    description: "Latest release or classic from preferred genre",
    priceMin: 15,
    priceMax: 30,
    tags: ["books", "sentimental", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  // More variety for 80+
  {
    title: "Plant in decorative pot",
    description: "Low-maintenance houseplant (e.g. pothos, snake plant) in ceramic pot",
    priceMin: 22,
    priceMax: 45,
    tags: ["home", "practical", "sentimental"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Cookbook (cuisine or diet-specific)",
    description: "Curated cookbook by theme (e.g. quick weeknight, baking)",
    priceMin: 20,
    priceMax: 40,
    tags: ["food", "practical", "kitchen"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Bluetooth speaker (compact)",
    description: "Water-resistant portable speaker, good battery life",
    priceMin: 35,
    priceMax: 65,
    tags: ["tech", "practical", "music"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Gourmet chocolate box",
    description: "Assorted artisan chocolates, 12–24 pieces",
    priceMin: 25,
    priceMax: 50,
    tags: ["food", "sentimental", "indulgence"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Scented candle (luxury)",
    description: "Single large candle from Diptyque, Jo Malone, or similar",
    priceMin: 45,
    priceMax: 75,
    tags: ["self_care", "home", "sentimental"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Water bottle (insulated)",
    description: "24oz insulated stainless steel, leak-proof",
    priceMin: 25,
    priceMax: 45,
    tags: ["practical", "fitness", "everyday"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Scarf or wrap",
    description: "Soft wool or cashmere blend scarf in neutral color",
    priceMin: 35,
    priceMax: 80,
    tags: ["clothing", "sentimental", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Cheese and cracker board set",
    description: "Bamboo board with knife and spreader; add cheese locally",
    priceMin: 28,
    priceMax: 50,
    tags: ["food", "experience", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Pajama set (cotton)",
    description: "Comfortable PJ set, unisex or women's/men's",
    priceMin: 32,
    priceMax: 55,
    tags: ["clothing", "self_care", "practical"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Notebook + fountain pen",
    description: "Mid-range fountain pen with ink and quality notebook",
    priceMin: 40,
    priceMax: 75,
    tags: ["writing", "sentimental", "practical"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Hot sauce or condiment set",
    description: "3-pack of artisan hot sauces or gourmet condiments",
    priceMin: 18,
    priceMax: 35,
    tags: ["food", "practical", "fun"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Massage gun (mini)",
    description: "Handheld percussion massager for muscles",
    priceMin: 35,
    priceMax: 60,
    tags: ["self_care", "fitness", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Succulent trio in pots",
    description: "Three small succulents in matching terracotta pots",
    priceMin: 22,
    priceMax: 40,
    tags: ["home", "practical", "sentimental"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Running or fitness belt",
    description: "Reflective belt with phone pocket for runs",
    priceMin: 18,
    priceMax: 35,
    tags: ["fitness", "practical", "sports"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Cocktail kit (starter)",
    description: "Shaker, jigger, strainer, and recipe booklet",
    priceMin: 30,
    priceMax: 55,
    tags: ["food", "experience", "adult"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "E-reader case + gift card",
    description: "Protective case plus $15 e-book credit",
    priceMin: 25,
    priceMax: 45,
    tags: ["tech", "books", "digital"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup", "digital"],
  },
  {
    title: "Charity donation in their name",
    description: "Donation to cause they care about, with card",
    priceMin: 20,
    priceMax: 100,
    tags: ["sentimental", "experience", "meaningful"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital"],
  },
  {
    title: "Desk plant (small)",
    description: "Small desk plant in modern pot (e.g. air plant, small succulent)",
    priceMin: 15,
    priceMax: 35,
    tags: ["home", "office", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Subscription snack box (1 month)",
    description: "One-time snack subscription box (e.g. SnackCrate, Graze)",
    priceMin: 25,
    priceMax: 45,
    tags: ["food", "subscription", "fun"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery"],
  },
  {
    title: "Luggage tag set",
    description: "4 leather or silicone luggage tags, customizable",
    priceMin: 15,
    priceMax: 30,
    tags: ["practical", "travel", "personalized"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Cold brew maker (pitcher)",
    description: "Large pitcher with filter for cold brew at home",
    priceMin: 22,
    priceMax: 40,
    tags: ["coffee", "practical", "kitchen"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Herb growing kit",
    description: "Seeds, pots, soil for basil, mint, parsley",
    priceMin: 20,
    priceMax: 38,
    tags: ["food", "practical", "home"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Puzzle (1000 pieces)",
    description: "Quality 1000-piece jigsaw, scenic or pop culture",
    priceMin: 18,
    priceMax: 35,
    tags: ["experience", "relaxation", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Reusable silicone food bags",
    description: "Set of 10–15 silicone bags, various sizes",
    priceMin: 18,
    priceMax: 32,
    tags: ["practical", "kitchen", "eco"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Mug with personalization",
    description: "Ceramic mug with name, quote, or inside joke",
    priceMin: 15,
    priceMax: 35,
    tags: ["sentimental", "coffee", "personalized"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Sleep mask + earplugs set",
    description: "Silk sleep mask and moldable earplugs in case",
    priceMin: 15,
    priceMax: 28,
    tags: ["self_care", "practical", "travel"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Local bakery gift card",
    description: "Gift card for local bakery or pastry shop",
    priceMin: 15,
    priceMax: 50,
    tags: ["food", "local", "last_minute"],
    urgencyCompatible: true,
    acquisitionTypes: ["digital", "pickup"],
  },
  {
    title: "Coloring book (adult) + pencils",
    description: "Intricate adult coloring book with colored pencil set",
    priceMin: 18,
    priceMax: 35,
    tags: ["self_care", "relaxation", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Pet treat or toy bundle",
    description: "Assorted treats and one toy for dog or cat",
    priceMin: 20,
    priceMax: 45,
    tags: ["pet", "practical", "fun"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Spice rack starter set",
    description: "6–8 essential spices in small jars with labels",
    priceMin: 25,
    priceMax: 45,
    tags: ["food", "kitchen", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Hand warmers (reusable)",
    description: "Rechargeable hand warmers for winter",
    priceMin: 22,
    priceMax: 40,
    tags: ["practical", "outdoor", "winter"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Recipe card box + blank cards",
    description: "Vintage-style recipe box with 50 blank cards",
    priceMin: 18,
    priceMax: 35,
    tags: ["sentimental", "kitchen", "keepsake"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "LED desk lamp (USB)",
    description: "Adjustable LED lamp with USB port",
    priceMin: 28,
    priceMax: 50,
    tags: ["practical", "office", "tech"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Honey sampler (3 varieties)",
    description: "Three small jars of different honey types",
    priceMin: 22,
    priceMax: 40,
    tags: ["food", "sentimental", "gourmet"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Dry shampoo + hair mask set",
    description: "Travel-size dry shampoo and hydrating hair mask",
    priceMin: 20,
    priceMax: 38,
    tags: ["self_care", "beauty", "practical"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Card game (party or strategy)",
    description: "Popular card game (e.g. Codenames, Sushi Go, Exploding Kittens)",
    priceMin: 15,
    priceMax: 30,
    tags: ["experience", "fun", "family"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Reusable water bottle (collapsible)",
    description: "Collapsible silicone bottle for travel",
    priceMin: 18,
    priceMax: 32,
    tags: ["practical", "travel", "eco"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Socks with fun pattern",
    description: "Comfortable socks with novelty pattern (animals, food, etc.)",
    priceMin: 12,
    priceMax: 25,
    tags: ["practical", "clothing", "fun"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Olive oil + balsamic set",
    description: "Small bottle of EVOO and flavored balsamic",
    priceMin: 28,
    priceMax: 50,
    tags: ["food", "gourmet", "practical"],
    urgencyCompatible: false,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Screen cleaning kit",
    description: "Microfiber cloths and safe spray for devices",
    priceMin: 12,
    priceMax: 25,
    tags: ["tech", "practical", "office"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
  {
    title: "Eucalyptus shower bundle",
    description: "Eucalyptus bundle to hang in shower + soap",
    priceMin: 18,
    priceMax: 32,
    tags: ["self_care", "spa", "wellness"],
    urgencyCompatible: true,
    acquisitionTypes: ["delivery", "pickup"],
  },
];

async function seed() {
  console.log("Seeding gift_catalog_items...");
  await db.insert(giftCatalogItems).values(items);
  console.log(`Inserted ${items.length} gift catalog items.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
